### ISSUE TITLE
Duda con ubicación de librería

### ISSUE THREAD

**Issue by asdenis** [genexuslabs/ExposureNotifications#1]
Copy the content of the Libraries folder to the corresponding Libraries folder under your GeneXus installation (eg: C:\Program Files (x86)\GeneXus\GeneXus16\Libraries

Puede ser que debería quedar así?
1. Create folder "**ExposureNorification**" in the Libraries folder under your GeneXus installation
2.  Copy the content of the Libraries folder to "**ExposureNorifications**" folder.
`C:\Program Files (x86)\GeneXus\GeneXus16\Libraries\ExposureNorifications\<content of the Libraries folder>`

**Comment by mcrispino** [comment]
Thank you Adrián for your feedback.
